### ISSUE TITLE
Handle a file for --template, or validate the input

### ISSUE THREAD

**Issue by edmundedgar** [gnosis/dao-module#25] opened 2021-05-20 06:44 UTC
We've had a couple of people showing up in the reality.eth discord saying their templates didn't work, it turned out they'd put the name of a file containing the template, when in fact they need the contents of the template.

I feel like the principle of least astonishment here would say to do what those people have expected, use the name of a file and automatically read the file in.

Failing that it might be good to at least put in some validation that the string we're using as a template looks like JSON. This is complicated by the fact that the templates only need to make valid json once the parameters are substituted in so attempting to parse it and erroring out if it fails might error our when it shouldn't.  It might be best just to do a crude check for that it begins with "{" and ends with "}", that should catch most of the mistakes.

**Comment by rmeissner** [comment] 2021-05-31 05:29
Duplicate of #21

**Closed by rmeissner** 2021-05-31 05:29 UTC
